
    version: '3.9'

    services:
      postgres:
        image: postgres:15
        container_name: postgres_cep
        environment:

          # Lê do .env
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          # Lê do .env

        ports:
          - "5434:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - cep-network
        restart: always # Se o servidor reiniciar, o container também reinicia

      # Configuração do Keycloak
      keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak_auth
        command: start-dev # Inicia o Keycloak em modo de desenvolvimento
        environment:
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
          - "8081:8080"



    volumes:
      postgres_data:

    networks:
      cep-network:
        driver: bridge



