#DATABASE CONFIGURATION

#Conecta direto na Render apenas com esse JDBC_DATABASE_URL, que já tem o username e password embutidos
spring.datasource.url=${JDBC_DATABASE_URL} 

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase configuration
spring.liquibase.change-log=liquibase/db.changelog-master.xml

server.port=8080

#A render lê as variáveis de ambiente e as disponibiliza para a aplicação, então podemos usar o JWT_SECRET diretamente aqui
api.security.token.secret=${JWT_SECRET}
