#DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5434/${DB_NAME:cep_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase configuration
spring.liquibase.change-log=liquibase/db.changelog-master.xml

server.port=8080

api.security.token.secret=${JWT_SECRET:1234}

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/cep-realm