name: Testes com Maven

on:
  # Gatilho: roda a cada push na branch main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código-fonte
        uses: actions/checkout@v4

      # 2. Configuração do Java
      - name: Configurar o Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # 3. Teste com mavem
      - name: Testar com Maven
        run: |
          chmod +x mvnw
          ./mvnw test

